spring:
  application:
    name: Aura-finance

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aura_finance}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
